/* File generated by:
	vpp.pl
    See link for more:
    https://www.beyond-circuits.com/wordpress/vpp-pl-man-page/
   
   Invoked by: Isaac Ogunmola
*/
`timescale 1ns/1ps

module word_mux(
    input   wire    [DATA_BLOCK_WIDTH-1:0]      i_block_data,
    input   wire    [BLOCK_OFFSET_BITS-1:0]     i_block_offset_bits,

    output  reg     [WORD_WIDTH-1:0]            o_word_data
);

    localparam DATA_BLOCK_WIDTH = 320;
    localparam BLOCK_OFFSET_BITS = 4;
    localparam WORD_WIDTH = 20;

    always @(*) begin
        case(i_block_offset_bits)

        20'd0  :   begin
            o_word_data = i_block_data[19:0];
        end

        20'd1  :   begin
            o_word_data = i_block_data[39:20];
        end

        20'd2  :   begin
            o_word_data = i_block_data[59:40];
        end

        20'd3  :   begin
            o_word_data = i_block_data[79:60];
        end

        20'd4  :   begin
            o_word_data = i_block_data[99:80];
        end

        20'd5  :   begin
            o_word_data = i_block_data[119:100];
        end

        20'd6  :   begin
            o_word_data = i_block_data[139:120];
        end

        20'd7  :   begin
            o_word_data = i_block_data[159:140];
        end

        20'd8  :   begin
            o_word_data = i_block_data[179:160];
        end

        20'd9  :   begin
            o_word_data = i_block_data[199:180];
        end

        20'd10  :   begin
            o_word_data = i_block_data[219:200];
        end

        20'd11  :   begin
            o_word_data = i_block_data[239:220];
        end

        20'd12  :   begin
            o_word_data = i_block_data[259:240];
        end

        20'd13  :   begin
            o_word_data = i_block_data[279:260];
        end

        20'd14  :   begin
            o_word_data = i_block_data[299:280];
        end

        20'd15  :   begin
            o_word_data = i_block_data[319:300];
        end


        default : begin
            o_word_data = {WORD_WIDTH{1'b0}};
        end
        endcase
    end

endmodule